fix: fix and optimize the logic around codecov (#66)
* package 📦: update dependencies to latest stable versions

Signed-off-by: Rigoberto L. Perez <rlperez@kablamo.me>

* ci 🤖: update pg versions to include 18

Signed-off-by: Rigoberto L. Perez <rlperez@kablamo.me>

* test 🧪: add purge queue tests

Signed-off-by: Rigoberto L. Perez <rlperez@kablamo.me>

* feat ✨: add purge queue function

Signed-off-by: Rigoberto L. Perez <rlperez@kablamo.me>

* chore 🧹: increment version

Signed-off-by: Rigoberto L. Perez <rlperez@kablamo.me>

* Revert "ci 🤖: update pg versions to include 18"

This reverts commit 1b9c95761553fc745cdbdb4f3289712b29ba9b43.

* docs 📚: update documentation to include new function

Signed-off-by: Rigoberto L. Perez <rlperez@kablamo.me>

* Revert "ci 🤖: update pg versions to include 18"

This reverts commit 1b9c95761553fc745cdbdb4f3289712b29ba9b43.

* ci 🤖: add in codecov token to master pipeline

Signed-off-by: Rigoberto L. Perez <rlperez@kablamo.me>

* ci 🤖: remove stray f added to doc task name

Signed-off-by: Rigoberto L. Perez <rlperez@kablamo.me>

* ci 🤖: update mise action

Signed-off-by: Rigoberto L. Perez <rlperez@kablamo.me>

* ci 🤖: remove codecov param and add logging

Signed-off-by: Rigoberto L. Perez <rlperez@kablamo.me>

* ci 🤖: remove codecov since it doesn't exist anymore

Signed-off-by: Rigoberto L. Perez <rlperez@kablamo.me>

---------

Signed-off-by: Rigoberto L. Perez <rlperez@kablamo.me>

diff --git a/.github/workflows/dependency_update.yml b/.github/workflows/dependency_update.yml
--- a/.github/workflows/dependency_update.yml
+++ b/.github/workflows/dependency_update.yml
@@ -20,7 +20,7 @@ jobs:
 
       - name: Update dependencies
         run: |
-          bb upgrade
+          bb upgrade || { echo "Dependency upgrade failed. Exiting."; exit 1; }
 
       - name: Verify authentication
         run: gh auth status
